[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/affiliate-disclosure.html"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/privacy.html"
  [headers.values]
    X-Robots-Tag = "noindex"
